title = 'The Realm of the Elder Dragons'
languageCode = 'en-us'
baseURL = 'https://eldra.org'
copyright = 'İbrahim Haras, Onur Can Şen'
disableHugoGeneratorInject = true
# hehe
# hehe2
# heheS
# heheE
# heheX
# asdasd
# qweqweq
# 123123123
# zxczxc
#123123
#1345346
[security]
[security.exec]
allow = ['^rst2html$']
